# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.hostname = 'm2-miage-drupal-9.local'
  config.vm.box = 'generic/ubuntu1804'
  
  config.ssh.insert_key = true
  
  config.vm.network "forwarded_port", 
    guest: 80, 
    host: 8090
  	
  config.vm.synced_folder '.', '/var/www', 
  create: true, 
  disabled: false, 
  owner: 'www-data', 
  group: 'www-data', 
  mount_options: ["dmode=775,fmode=664"]
  
  config.vm.provider "virtualbox" do |vb|
	vb.name = 'M2 MIAGE - Drupal 9'
	vb.memory = 1024
	vb.cpus = 2
  end
    
  config.vm.provision 'shell', path: 'provision.sh'
end